# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/analysisWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_analysisDialog(object):
    def setupUi(self, analysisDialog):
        analysisDialog.setObjectName("analysisDialog")
        analysisDialog.resize(1169, 438)
        self.groupBox = QtWidgets.QGroupBox(analysisDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 551, 421))
        self.groupBox.setObjectName("groupBox")
        self.graphicsView_noise = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_noise.setGeometry(QtCore.QRect(10, 20, 531, 351))
        self.graphicsView_noise.setObjectName("graphicsView_noise")
        self.pushButton_noise = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_noise.setGeometry(QtCore.QRect(200, 380, 121, 31))
        self.pushButton_noise.setObjectName("pushButton_noise")
        self.groupBox_2 = QtWidgets.QGroupBox(analysisDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(600, 10, 551, 421))
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView_enhanced = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_enhanced.setGeometry(QtCore.QRect(10, 20, 531, 351))
        self.graphicsView_enhanced.setObjectName("graphicsView_enhanced")
        self.pushButton_enhanced = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_enhanced.setGeometry(QtCore.QRect(220, 380, 121, 31))
        self.pushButton_enhanced.setObjectName("pushButton_enhanced")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(analysisDialog)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("analysisDialog", "带噪音频"))
        self.pushButton_noise.setText(_translate("analysisDialog", "播放"))
        self.groupBox_2.setTitle(_translate("analysisDialog", "增强音频"))
        self.pushButton_enhanced.setText(_translate("analysisDialog", "播放"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    analysisDialog = QtWidgets.QDialog()
    ui = Ui_analysisDialog()
    ui.setupUi(analysisDialog)
    analysisDialog.show()
    sys.exit(app.exec_())
